#!/usr/bin/env bash

[[ ! -x $(command -v git) ]] && echo "you're gonna need git installed" && exit 1

here=$(git rev-parse --show-toplevel)

targets=(bash_profile bashrc profile)
for t in "${targets[@]}" ; do
    src="$here/$t"
    dst="$HOME/.$t"
    [[ -f "$dst" ]] && [[ ! "$here" -ef "$dst" ]] && mv "$dst" "$dst.bak"
    ln -sf "$src" "$dst"
done
